FROM victorialservera31/desktop:latest

# Set environment variables to avoid interactive prompts
#ENV DEBIAN_FRONTEND=noninteractive

# Actualizar los paquetes e instalar  las dependencias necesarias
RUN apt update && \
    apt-get install -y python3 python3-pip spyder3 python3-pyqt5 python3-pyqt5.qtwebengine && \
    apt-get clean
# Configurar variables de entorno para desactivar la integración de OpenGL con XCB en Qt
RUN echo "export QT_XCB_GL_INTEGRATION=none" >> /etc/profile.d/qt-xcb-gl-integration.sh