apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.podName }}-service-codeblocks
spec:
  selector:
    app: {{ .Values.podName }}-codeblocks
  ports:
    - name: "rdp"
      protocol: TCP
      port: 3389
      targetPort: 3389
      nodePort: 3389
  type: NodePort
