apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.podName }}-vsc
  labels:
    app: {{ .Values.podName }}-vsc
spec:
  containers:
  - name: {{ .Values.podName }}-vsc
    image: victorialservera31/vsc:latest
    ports:
    - containerPort: 3389  # puerto RDP
    command: 
    - "/bin/sh"
    - "-c"
    - |
      service ssh start && service xrdp restart && sleep infinity
    volumeMounts:
    - mountPath: /shared_home
      name: home-storage
    - mountPath: /{{ .Values.podName }}
      name: {{ .Values.podName }}-home
  volumes:
      - name: home-storage
        nfs:
          server: "{{ .Values.ip_server }}"
          path: "/mnt/shared_home"
      - name: {{ .Values.podName }}-home
        persistentVolumeClaim:
          claimName: pvc-{{ .Values.podName }}

{{- if eq .Values.ip_server "" }}
{{- fail "Es obligatorio indicar la IP del server NFS. Es la IP con la que has accedido al catálogo Kubeapps." }}
{{- end }}